### ISSUE TITLE
POC: Replace popper.js with native support

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-dropdown#218]
### Discussed in https://github.com/AlaskaAirlines/WC-Generator/discussions/507

<div type='discussions-op-text'>

<sup>Originally posted by **blackfalcon** June  1, 2023</sup>
> @Totati and @mfreed7 thanks a lot for this issue and for alerting us of the problem. Sorry, were unable to release an update prior to the 114 release of Chrome, but when we discovered the problem, we were presently surprised to find this issue with the fix outlined.
> 
> Thanks again! OSS FOR THE WIN!

Great news! Thanks for the update, and for updating Auro so quickly.

You might also look into the [new Popover API](https://developer.chrome.com/blog/introducing-popover-api/) as a replacement for the popover functionality in Auro. I'd be curious to hear your feedback about the feature and see if it can reduce the JS required to implement popovers.

_Originally posted by @mfreed7 in https://github.com/AlaskaAirlines/auro-popover/issues/42#issuecomment-1572693084_

### Additional context

The new API is out in the latest release of Chrome, but we will require additional browser support before considering this feature. 

https://caniuse.com/?search=popover
            </div>

**Comment by Patrick-Daly-AA** [comment]
Initial goal for this issue is to determine the viability of using native support.
Just spinning up a new repo with generator for a simple component with native popover and ensure there's a slot for a trigger and a slot for the content, and then see if it is usable in combobox or datepicker (don't worry about styling, that'll come later), and nothing explodes.
