### ISSUE TITLE
Reverse perceived API option 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-dropdown#90]
The following code addresses the option of a toggle open/close click on the trigger. 

https://github.com/AlaskaAirlines/auro-dropdown/blob/c78403cefe932b5388a787ff3203c448b5504e07/src/auro-dropdown.js#L153-L159

I am of the opinion that this should be set by default and the user would elect to disable the toggle feature if needed. 

AC:  
- Toggle should be the default experience
- Need to have a 'notoggle' attribute
- deprecate 'toggle'

**Comment by braven112** [comment]
Let's go over this with the ui designers and product designers, let's come up with the different scenario's and get feedback.

**Comment by leeejune** [comment]
After discussion with the UI designers, I got feedback that the default should be the toggle experience. Here are some reasons for it:
1. It is an already established experience that is intuitive
2. Suggest has the toggle behavior; since the two look the same, the users will be expecting the same behavior
3. There is no benefit of NOT having the toggle while having the toggle allows users to interact with the component in more ways

**Comment by blackfalcon** [comment]
Based on @leeejune feedback, I feel that we can get this in the `ready to dev` pipeline.
